### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by Knightro63** [FlutterGL/flutter_web_gl#17]
Hi @escamoteur,

I want to know before I put in a pull request if this is still being maintained?

I was able to get web working with one issue that is it is upside-down. 

I was also able to get this repo slightly working on three_dart with many bugs and crashes. Web works flawlessly, macos issue with source textures like instancing and shadows, ios random crashes, windows same as macos, and I have not tried android. 

Thanks

**Comment by escamoteur** [comment]
hi @Knightro63 unfortunately I don't have currently any time to maintain this project and as I don't need any OpenGL stuff in my daily work anymore I don't see mee returning to it anytime soon.
If you are interested in taking over, you are welcome

**Comment by Knightro63** [comment]
Hi @escamoteur,

Thanks for getting back to me. 

I will create a new repo.
