### ISSUE TITLE
android support 

### ISSUE THREAD

**Issue by wasabia** [FlutterGL/flutter_web_gl#9]
Hi
now this plugin create EGLContext use dart ffi then pass (int pointer ?) to native convert back to Native EGLContext Object

but on Android i can't find method to convert EGLContext int back to Android Native EGLContext use java or kotlin
```
public class EGLContext extends EGLObjectHandle {
    EGLContext(long handle) {
        super(0);
        throw new RuntimeException("Stub!");
    }

    public boolean equals(Object o) {
        throw new RuntimeException("Stub!");
    }
}
```

maybe we need create EGLContext on Native side then pass to dart

**Comment by escamoteur** [comment]
Hi, Android is indeed quite different in that but I didn't have the time yet to take a closer look. will do later today.

**Comment by escamoteur** [comment]
Android is now supported although only with one Texture.
